name: Dispatch

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Disparar evento para outro repositório
        env:
          TOKEN: ${{ secrets.GTH_TOKEN  }} # Substitua 'PAT' pelo nome da sua secret que contém o PAT
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token $TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/g12-4soat/techlanches-infra-k8s/actions/workflows/dispatch.yml/dispatches \
          -d '{"ref":"teste-dispatch"}'
