name: Pipeline techlanches-app

on:
  push:  
  workflow_dispatch:
  
jobs:

##############################################################
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Restore NuGet packages
        run: dotnet restore **/**/*.csproj

      - name: Build
        run: dotnet build **/**/*.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test test/**/*.csproj --no-restore --verbosity normal

##############################################################

  publish-api-image-dh:
    needs: build-and-test

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
      - name: Build and Push API Image
        working-directory: src/TechLanches
        run: |
          TAG=$(date +%Y%m%d%H%M%S)
          docker build -f Dockerfile.API -t ${{secrets.DOCKER_USERNAME}}/techlanches-app:latest -t ${{secrets.DOCKER_USERNAME}}/techlanches-app:$TAG . --no-cache
          docker push ${{secrets.DOCKER_USERNAME}}/techlanches-app:$TAG
          docker push ${{secrets.DOCKER_USERNAME}}/techlanches-app:latest      

  publish-worker-image-dh:
    needs: build-and-test

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
      - name: Build and Push Worker Image
        working-directory: src/TechLanches
        run: |
          TAG=$(date +%Y%m%d%H%M%S)
          docker build -f Dockerfile.Worker -t ${{secrets.DOCKER_USERNAME}}/techlanches-app-worker:latest -t ${{secrets.DOCKER_USERNAME}}/techlanches-app-worker:$TAG . --no-cache
          docker push ${{secrets.DOCKER_USERNAME}}/techlanches-app-worker:$TAG
          docker push ${{secrets.DOCKER_USERNAME}}/techlanches-app-worker:latest
##############################################################

  deploy-prod:   
  
    needs: [
      publish-api-image-dh,
      publish-worker-image-dh
    ]
  
    if: github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main'
    environment:
      name: prod
    
    runs-on: ubuntu-latest

    steps:
      - name: Deploy AWS
        run: |
          echo "Deploy AWS"
